Added example for the interpolation documentation.
pmndrs/react-spring pull request #1984
Opened 2022-09-20 21:37 UTC by anshullaikar

### Why

The docs for [interpolation](https://react-spring.dev/common/interpolation#interpolations) are missing the `to` function implementation. I had to go through some examples to figure out how to use the `to` function. My addition to the docs should help other people who are facing a similar issue.

### What

Have added an example of an implementation of `to` which helps explain it's use case with `useTransition` as well.  Please let me know if any changes are required in the formatting.

### Checklist

- [x] Documentation updated
- [x] Demo added
- [x] Ready to be merged

2022-09-22 12:28 UTC, anshullaikar commented
@joshuaellis Any comments?

2022-09-22 12:36 UTC, anshullaikar commented
@joshuaellis any comments?

2022-09-25 07:34 UTC, anshullaikar commented
Have updated the commit message and PR title as per the Conventional Commit guidelines

2022-09-25 13:20 UTC, joshuaellis requested changes
These examples are overly complicated e.g. why are are mapping `elements` in this example? Then you just pass "settings" it's all too vague as well.

In the first example i'd argue the use of the `to` function is superfluous when you can just do `styles.y.to` and then you're passing the `key` object which you don't need to do so that's incorrect.

IMO these examples should be thorough and simple.

2022-09-29 20:16 UTC, joshuaellis commented
Closing this because i've added some documentation around this on the new doc site – https://beta.react-spring.dev/docs/advanced/interpolation

2022-09-29 20:16 UTC, closed without merging

2022-09-30 19:49 UTC, anshullaikar commented
@joshuaellis Wow, the new documentation site looks great! And thanks for the feedback, will add simpler examples if I think of any other documentation PRs :slightly_smiling_face: