docs: Update preset section on spring config
pmndrs/react-spring pull request #1999
Opened 2022-10-15 09:37 UTC by heyfirst

### Why
I see a lot of value from [this preset section](https://react-spring.dev/common/configs#presets) in old docs. I believe it would be nice if we can have similar thing in new docs as well.

### What
- Move preset section to be under the config visualization
- Add preset visualization with the same idea of [original preset section](https://react-spring.dev/common/configs#presets)

### Checklist
- [x] Documentation updated
- [x] Demo added
- [x] Ready to be merged

### Comments
Here is my first time coding in remix and `jsx` tag on MDX. It is really cool that we can define a code on MDX and automatically run on codesandbox. That's brilliant!

2022-10-17 09:46 UTC, joshuaellis requested changes
Small change, i'm wondering if we should combine the preset visualiser and the config editor, do you see any value in keeping them separate?

2022-10-17 09:46 UTC, joshuaellis commented on docs/app/routes/docs/advanced/config.mdx
> +import { useRef, useState } from 'react'
useState isn't being used, I think we should remove this.

2022-10-17 10:54 UTC, heyfirst commented
@joshuaellis Good point! I didn't see any value to separate it either. I will update to add one more preset option to the config visualizer above. Will ping you once it's ready to review :)

2022-10-24 19:55 UTC, heyfirst commented
Sorry for super-long silence, I have been into some initiatives on my current work, many things to catchup, I will update this PR on this weekend.

2024-05-26 19:04 UTC, joshuaellis commented
closing due to inactivity

2024-05-26 19:04 UTC, closed without merging