support removing attributes from animated elements
pmndrs/react-spring pull request #2293
Opened 2024-06-13 14:38 UTC by LoganDark

### Why

[`inert`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) does not accept `inert=''`, `inert='false'`, `inert='undefined'` or etc. The attribute ***must*** be entirely removed in order to enable the element again.

### What

If a value resolves to `undefined` (not `null` or `false` or otherwise) its attribute will now be entirely removed.

### Checklist

- [x] Ready to be merged

2024-06-25 09:17 UTC, joshuaellis requested changes
Before we can evaluate on this being the right thing to do properly, can we add a couple of test cases to `animated.test.tsx` that shows this working please? :)

2024-06-25 09:19 UTC, LoganDark commented
I suppose right now it's impossible for a spring value to even be `null` or `undefined` without an interpolation, because of #2295. I'm off work for the week, so I can look into this more next Monday.

2024-09-16 15:41 UTC, joshuaellis commented
@LoganDark can you rebase this please? :)

2024-09-16 15:41 UTC, closed without merging

2024-09-16 15:42 UTC, LoganDark commented
oh oops I didn't realize I had another PR open, lmao, one moment

2024-09-16 15:59 UTC, LoganDark commented
#2319